### ISSUE TITLE
VideoAutoFlipper script crashes after clicking on VFX/Helpers/FAQ tabs

### ISSUE THREAD

**Issue by b3ldin** [Zly-u/zly_reapack#7]
Then opens an error window with ReaScript title: 
> ...ack Repo\Video\VideoAutoFlipper\Zly_VideoAutoFlipper.lua:__1068__: bad argument #5 to 'BeginChild' (number expected, got boolean)
![image](https://github.com/Zly-u/zly_reapack/assets/71645467/2e7fe507-44aa-401e-9ca6-428497a2da76)
(also clicking on "VFX" would returns line __1068__ in error window, "Helpers" returns __1240__ line and "FAQ" returns __1408__ line)

After closing this window, new one appears:
> (g.CurrentWindowStack.Size == 1) && "Mismatched Begin/BeginChild vs End/EndChild calls: did you forget to call End/EndChild?"
![image](https://github.com/Zly-u/zly_reapack/assets/71645467/4113da67-e1f8-4bd3-924e-e30843fecd22)

i guess ReaImGui just got updated or something, i tried putting a `require 'imgui' '0.9.0.2'` line in top of the script but nothing really changed, idk what happened im not that smart to figure out reaper's nonsense lol

**Comment by Zly-u** [comment]
Yeah, seems like ReaImGui got updated, will fix in a bit.

**Comment by Zly-u** [comment]
Should be fixed now, try to update.

**Comment by Zly-u** [comment]
Also, to temporarily fix it, you could download an older version of `ReaImGui` in the `Reapack`.
Telling this just for the future cases like that, so you don't have to wait for fixes.

**Comment by b3ldin** [comment]
Updating the script worked, thank you!
